### ISSUE TITLE
Files Texteditor bug while editing the file during the auto-save

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/files_texteditor#23]
Hi there,
I'll get the following Error when I edit a text file.

> {"reqId":" *** ","remoteAddr":" *** ","app":"files_texteditor","message":"File: \/test.txt modified since opening.","level":3,"time":"2016-12-17T13:15:33+01:00","meth$

How to reproduce:

1. Create a new .txt file
2. Open the created .txt file
3. Write something & save it (Strg + s)
4. Edit the .txt file and dont stop to write/edit while nextcloud will auto-save the .txt file

Operating System:
Ubuntu 16.04 LTS
Apache 2.4.18
PHP 7.0.8
Nextcloud 11.0.0

redis-cache? Yes
--> config.php:

'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\Redis',
'redis' =>
array (
'host' => '/var/run/redis/redis.sock',
'port' => 0,
'timeout' => 0.0,
),

Are sync clients running? Yes

Is the file/folder shared? No

[https://help.nextcloud.com/t/app-files-texteditor-bug/6353](https://help.nextcloud.com/t/app-files-texteditor-bug/6353)

**Comment by nickvergessen** [comment]
Can reproduce this aswell, also without redis. This happens when auto-save and manual-save are done in parallel.
I'd just ignore it for now, but maybe we can fix it, so the auto-save is not triggered, while manual saving is still in progress

**Comment by girst** [comment]
Same here; NextCloud 11 on FreeNAS 9.10. Redis is enabled. 

Whenever a document auto-saves, it creates an error in the log. 

This is very annoying, as it hides important error messages in the flood of those comming from files_texteditor. 

No sync clients running, and the folder isn't shared.

**Comment by nickvergessen** [comment]
@icewind1991 can you have a look?

**Comment by Azd325** [comment]
Can reproduce this as well.
Is there a way that we can change the error level of this?

**Comment by Ciiss0u** [comment]
I've also ofter this problem.
Error "cannot save..." appears but file is saved.

Rebooting server seems solve it.

I'll check if flushing redis instead of reboot solves that. or truncate file_locks table.

**Comment by Konfuz** [comment]
Can reproduce with both Nextcloud 11.0.3. and Nextcloud 11.0.2 
`'memcache.local' => '\\OC\\Memcache\\APCu'`
all other memcache settings on default.

**Comment by contribguy** [comment]
Hi!
I've just started using my fresh nextcloud installation a couple of days ago.

Yesterday I installed the markdown-editor plugin and today I edited a test-file and saw the same error messages in my logfile.

Maybe the auto-save function could save the document when the user stopped writing, e.g. five seconds after last change?

Running Nextcloud 11.0.3.
No sync-client running at the moment this happened.

**Comment by contribguy** [comment]
Forgot to mention, I have no cache activated.

**Comment by SuperSayu** [comment]
#67 has been open for three weeks with no sign of interest, so I will say that if you desperately need a workaround, that change to the javascript helps with the problem considerably, if it doesn't fix it entirely.  In short, the autosave was broken and was spamming the server.

**Comment by MorrisJobke** [comment]
Fixed via #67

**Comment by Bellusterra** [comment]
I'm still getting this error. Both .md and .txt files from notes and markdown editor are saying save failed

**Comment by Bellusterra** [comment]
okay, so it appears that it is the music app that is somehow interfering with the saving of the files in the text editor apps like notes, markdown etc. so disabling that fixed the problem and everything saves as normal, I'll report it to the app developer. hope this helps if anyone else is having the same issue

**Comment by jknockaert** [comment]
Getting this error with NC 16.0.1.

**Comment by rteitge** [comment]
> 
> 
> I'm still getting this error. Both .md and .txt files from notes and markdown editor are saying save failed
> I have the latest version of nextcloud with php 7.2 on apache with redis and apcu.

I can confirm with 16.0.4

**Comment by sundowndev** [comment]
Same issue here 👋

**Comment by Dellyjoe** [comment]
Hello everyone, I seem to also have the issue, I Have Nextcloud 19.0.1 and Markdown Editor 2.3.0  and  Plain text editor 2.11.0.

When looking at #67 I don't know where that file would be (js/editor.js )?
 I'm using Freenas 11.3 and I have nextcloud in a jail.

I'm new at this, but can edit a text file :)

Any help would be great,
Thank you,
Joe

**Comment by sokai** [comment]
Here is another configuration that throws that "Fatal" messages in the log while editing a ".md" file using the web UI … :-|

I haven't installed or enabled the "Music" app.
I have installed this app ("Plain text editor") in version 2.11.0.
I have also installed and enabled the ["Markdown Editor" app](https://apps.nextcloud.com/apps/files_markdown) (v2.3.0).

```json
{
  "reqId": "8YdLdqRSZ2ozEySgYuIV",
  "level": 4,
  "time": "2020-09-07T13:41:57+02:00",
  "remoteAddr": "[ANON-IPv6]",
  "user": "[ANON-ACCOUNT]",
  "app": "files_texteditor",
  "method": "PUT",
  "url": "/index.php/apps/files_texteditor/ajax/savefile",
  "message": "File: [ANON-FILE] modified since opening.",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
  "version": "19.0.2.2"
}
```

Plz reopen that issue (or create a new one?) and fix that error. Thanks in advance! :-)

**Comment by bertrand-benoit** [comment]
Same issue with Nextcloud 21 ... what is the solution?
