### ISSUE TITLE
Please add compatibility with NC25

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_texteditor#620]
This app continues to be useful even on current versions of nextcloud.

Could you please make it compatible with the most recent NC25?

**Comment by sn0n** [comment]
Does this work with NC25? Following

**Comment by christianlupus** [comment]
@juliushaertl is there a plan to stop supporting the plain text editor and instead "force" users to use the normal text editor? Or might there be a merge of the features be possible in the future?

**Comment by juliushaertl** [comment]
I just released a new version to the app store to cover 25 compatiblility. Sorry for taking so long. I mainly stepped in after we switched to the rich text editor by default to keep the app available but lack time to maintain and do the releases. I'll discuss internally on how we want to proceed with that.

**Comment by elpraga** [comment]
@juliushaertl it is great that this app still exists, as it allows editing the files directly, as sometimes it is needed.

**Comment by christianlupus** [comment]
Thank you very much

Please keep us posted on case there is a change in the official rules/best-practices.
